import { ActivityType } from "discord.js";
export const botOwners: string[] = JSON.parse(process.env.OWNERS!);
export const botPrefix = process.env.PREFIX ?? "t!";
export const botActivity = process.env.ACTIVITY ?? "For demons";
export const botEmbedColor = "#A7D129";
export const botActivityType: Exclude<ActivityType, "CUSTOM"> = (process.env.ACTIVITY_TYPE as Exclude<ActivityType, "CUSTOM">)! ?? "WATCHING";
export const redisUsername: string = process.env.REDIS_USERNAME!;
export const redisPassword: string = process.env.REDIS_PASSWORD!;
export const redisPort = Number(process.env.REDIS_PORT!);
export const redisHost: string = process.env.REDIS_HOST!;
export const apiPort: number = process.env.PORT as unknown as number ?? 3000;
export const apiAuthorization: string = process.env.API_AUTH!;